INFO:__main__:Preparing data...
INFO:__main__:Creating model...
INFO:__main__:Starting training...
Training:   0%|                                                                                                                  | 0/157 [00:00<?, ?it/s]/home/blvksh33p/Documents/models/missing_data_imputation/src/models/hybrid.py:85: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:278.)
  beliefs_tensor = torch.tensor(
/home/blvksh33p/Documents/models/missing_data_imputation/src/models/hybrid.py:107: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3683.)
  continuous_predictions = (beliefs_tensor @ value_points).T
Training:   0%|                                                                                                                  | 0/157 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/train.py", line 267, in <module>
    main(args.config)
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/train.py", line 172, in main
    history = trainer.train(
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/experiments/trainer.py", line 142, in train
    train_metrics = self._train_epoch(gradient_clip_val)
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/experiments/trainer.py", line 190, in _train_epoch
    outputs = self.model(x, mask)
  File "/home/blvksh33p/Documents/models/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/blvksh33p/Documents/models/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/models/hybrid.py", line 121, in forward
    bn_predictions = bn_predictions.view(vae_outputs['imputed'].shape)
RuntimeError: shape '[64, 20]' is invalid for input of size 20
Traceback (most recent call last):
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/train.py", line 267, in <module>
    main(args.config)
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/train.py", line 172, in main
    history = trainer.train(
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/experiments/trainer.py", line 142, in train
    train_metrics = self._train_epoch(gradient_clip_val)
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/experiments/trainer.py", line 190, in _train_epoch
    outputs = self.model(x, mask)
  File "/home/blvksh33p/Documents/models/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/blvksh33p/Documents/models/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/blvksh33p/Documents/models/missing_data_imputation/src/models/hybrid.py", line 121, in forward
    bn_predictions = bn_predictions.view(vae_outputs['imputed'].shape)
RuntimeError: shape '[64, 20]' is invalid for input of size 20
